api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  formats:
    json: ['application/json']
    xml: ['application/xml', 'text/xml']
    html: ['text/html']
  title: 'e-Shopping REST API'
  version: 1.0.0
  collection:
    pagination:
      client_items_per_page: true
      items_per_page: 4
